export const vacancies = [
  {
    id: '1',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс "Мидл фронтенд-разработчик"',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 35 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-42',
  },
  {
    id: '2',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Python‑разработчик» (ищем только в резерв)',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-17',
  },
  {
    id: '3',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Разработчик C++»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 35 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-29',
  },
  {
    id: '4',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Java‑разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-59',
  },
  {
    id: '5',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Алгоритмы для разработчиков»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 35 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-47',
  },
  {
    id: '6',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Инженер по тестированию»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-3',
  },
  {
    id: '7',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Android‑разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц (уточнить)',
    url: 'https://practicum.yandex.ru/job/vacancy-83',
  },
  {
    id: '8',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «iOS‑разработчик»',
    textPay: 'Оплата за ведение группы',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц (уточнить)',
    url: 'https://practicum.yandex.ru/job/vacancy-84',
  },
  {
    id: '9',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Мидл Python‑разработчик» (ищем только в резерв)',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-45',
  },
  {
    id: '10',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Go‑разработчик» (ищем только в резерв)',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-58',
  },
  {
    id: '11',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «DevOps»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-65',
  },
  {
    id: '12',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Асинхронно программирование на Python»',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-29',
  },

  {
    id: '13',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Аналитик данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц (уточнить)',
    url: 'https://practicum.yandex.ru/job/vacancy-5',
  },
  {
    id: '14',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Специалист по Data Science»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц (уточнить)',
    url: 'https://practicum.yandex.ru/job/vacancy-6',
  },
  {
    id: '15',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Системный аналитик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц (уточнить)',
    url: 'https://practicum.yandex.ru/job/vacancy-90',
  },
  {
    id: '16',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Инженер данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц (уточнить)',
    url: 'https://practicum.yandex.ru/job/vacancy-77',
  },
];