export const vacancies = [
  {
    id: '1',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс "Мидл фронтенд-разработчик"',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 35 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-42',
  },
  {
    id: '2',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Python‑разработчик» (ищем только в резерв)',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-17',
  },
  {
    id: '3',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Разработчик C++»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 35 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-29',
  },
  {
    id: '4',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Java‑разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-59',
  },
  {
    id: '5',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Алгоритмы для разработчиков»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 35 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-47',
  },
  {
    id: '6',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Инженер по тестированию»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-3',
  },
  {
    id: '7',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Android‑разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-83',
  },
  {
    id: '8',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «iOS‑разработчик»',
    textPay: 'Оплата за ведение группы',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-84',
  },
  {
    id: '9',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Мидл Python‑разработчик» (ищем только в резерв)',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-45',
  },
  {
    id: '10',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Go‑разработчик» (ищем только в резерв)',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-58',
  },
  {
    id: '11',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «DevOps»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-65',
  },
  {
    id: '12',
    role: 'mentor',
    specs: 'programming',
    title: 'Наставник на курс «Асинхронно программирование на Python»',
    textPay: 'Оплата за ведение группы',
    textCash: 'От 50 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-29',
  },

  {
    id: '13',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Аналитик данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-5',
  },
  {
    id: '14',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Специалист по Data Science»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-6',
  },
  {
    id: '15',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Системный аналитик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-90',
  },
  {
    id: '16',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Инженер данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-77',
  },

  {
    id: '36',
    role: 'mentor',
    specs: 'analitics',
    title: 'Наставник на курс «Инженер данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-77',
  },
  {
    id: '17',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс React-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-63',
  },
  {
    id: '18',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Веб-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-77',
  },
  {
    id: '19',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Python-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-20',
  },
  {
    id: '20',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Java-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-73',
  },
  {
    id: '21',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «iOS-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-85',
  },
  {
    id: '22',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Мидл Python-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-40',
  },
  {
    id: '23',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Инженер по тестированию»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-36',
  },
  {
    id: '24',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Android-разработчик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-89',
  },
  {
    id: '25',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер по Go на курс «Алгоритмы для разработчиков»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-34',
  },
  {
    id: '26',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер по Python на курс «Алгоритмы для разработчиков»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-32',
  },
  {
    id: '27',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер по Java на курс «Алгоритмы для разработчиков»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-33',
  },
  {
    id: '28',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Асинхронно программирование на Python»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-95',
  },
  {
    id: '29',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Разработчик на С++»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-43',
  },
  {
    id: '30',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер на курс «Автоматизатор тестирования на Java»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-75',
  },
  {
    id: '31',
    role: 'review',
    specs: 'programming',
    title: 'Ревьюер по С++ на курс «Алгоритмы для разработчиков»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-35',
  },
  {
    id: '32',
    role: 'review',
    specs: 'analitics',
    title: 'Ревьюер на курс «Системный аналитик»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-93',
  },
  {
    id: '33',
    role: 'review',
    specs: 'analitics',
    title: 'Ревьюер на курс «Инженер данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-82',
  },
  {
    id: '34',
    role: 'review',
    specs: 'analitics',
    title: 'Ревьюер на курс «Аналитик данных»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-37',
  },
  {
    id: '35',
    role: 'review',
    specs: 'analitics',
    title: 'Ревьюер на курс «Специалист по Data Science»',
    textPay: 'Оплата за ведение группы',
    textCash: 'В среднем 45 000 ₽ в месяц',
    url: 'https://practicum.yandex.ru/job/vacancy-38',
  },
];